services:
  # Our database management system
  db-0:
    environment:
      MARIADB_USER: &dbuser todo
      MARIADB_PASSWORD: &dbpass todosecret
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: &dbname VideoMicroservice
  
  db-1:
    environment:
      MARIADB_USER: &dbuser todo
      MARIADB_PASSWORD: &dbpass todosecret
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: &dbname TrendingHashtagMicroservice
  
  db-2:
    environment:
      MARIADB_USER: &dbuser todo
      MARIADB_PASSWORD: &dbpass todosecret
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: &dbname SubscriptionMicroservice

  # Our microservice, built with './gradlew dockerBuild'
  VideoMicroservice:
    environment:
      DB_USER: *dbuser
      DB_PASSWORD: *dbpass
      DB_NAME: *dbname
  
  TrendingHashtagMicroservice:
    environment:
      DB_USER: *dbuser
      DB_PASSWORD: *dbpass
      DB_NAME: *dbname
  
  SubscriptionMicroservice:
    environment:
      DB_USER: *dbuser
      DB_PASSWORD: *dbpass
      DB_NAME: *dbname
