micronaut:
  application:
    name: SubscriptionMicroservice
  server:
    port: 8082
datasources:
  default:
    url: jdbc:mariadb://${DB_HOST:`localhost:3308`}/${DB_NAME:SubscriptionMicroservice}
    username: ${DB_USER:todo}
    password: ${DB_PASSWORD:todosecret}
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
jpa:
  default:
    entity-scan:
      packages:
        - assessment.domain
    properties:
      hibernate:
        show_sql: ${DEBUG_SQL:false}
        format_sql: ${DEBUG_SQL:false}
        hbm2ddl:
          auto: update
netty:
  default:
    allocator:
      max-order: 3
kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9094`}